timeout: 1800s
steps:
  # Terraform init and plan
  - name: hashicorp/terraform:latest  # Public image with Terraform
    entrypoint: /bin/sh
    args:
      - '-c'
      - |-
        terraform init -input=false
        terraform plan -input=false -lock-timeout=60s -out=tfplan

options:
  machineType: 'E2_HIGHCPU_8'

artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/plan/${BUILD_ID}'
    paths: ['tfplan']
