timeout: 1800s
steps:
  # Step 1: Install Terraform
  - name: hashicorp/terraform:latest
    entrypoint: /bin/sh
    args:
      - '-c'
      - |-
        terraform --version

  # Step 2: Initialize Terraform
  - name: hashicorp/terraform:latest
    entrypoint: /bin/sh
    args:
      - '-c'
      - |-
        terraform init -input=false

  # Step 3: Create Terraform Plan
  - name: hashicorp/terraform:latest
    entrypoint: /bin/sh
    args:
      - '-c'
      - |-
        terraform plan -input=false -out=tfplan
